version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev